### ISSUE TITLE
Team-102-the-Cetus

### ISSUE THREAD

**Issue by phylischumba** [alishabab/bheem-rpg#2]
Hey @alishabab,

This is great work, your capstone game project looks fantastic. You have a good understanding and flow of your code, the presentation was exceptional. Wishing you the very best as you finish up on the project.

Good luck!!

**Comment by alishabab** [comment]
![bheem](https://user-images.githubusercontent.com/33728992/91640075-a37a7080-ea38-11ea-8b3d-d89850831a8e.PNG)

**Comment by alishabab** [comment]
![game-play](https://user-images.githubusercontent.com/33728992/91640795-bba0be80-ea3d-11ea-91b5-90c92d46f876.gif)

**Comment by alishabab** [comment]
![characters](https://user-images.githubusercontent.com/33728992/91641014-4930de00-ea3f-11ea-94b6-3305508728af.png)

**Comment by alishabab** [comment]
![preload](https://user-images.githubusercontent.com/33728992/91641051-8f863d00-ea3f-11ea-8e17-f30addee5354.PNG)

**Comment by alishabab** [comment]
![title](https://user-images.githubusercontent.com/33728992/91641084-c3f9f900-ea3f-11ea-9c08-f92058a12530.PNG)

**Comment by alishabab** [comment]
![gameplay](https://user-images.githubusercontent.com/33728992/91641137-10ddcf80-ea40-11ea-81cd-3cbaa359834c.PNG)
